apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cost-analyzer-service-role
rules:
  - apiGroups: [ "", "admissionregistration.k8s.io" ]
    resources: [ "mutatingwebhookconfigurations", "pods", "nodes" ]
    verbs: [ "get", "create", "patch", "list", "update" ]