apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 1
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - image: jcchavezs/httpmole
          name: demoapp
          ports:
            - name: http
              containerPort: 10080
